return {
  -- {
  --   "piersolenski/wtf.nvim",
  --   dependencies = {
  --     "nvim-lua/plenary.nvim",
  --     "MunifTanjim/nui.nvim",
  --     "nvim-telescope/telescope.nvim",
  --   },
  --   opts = {},
  --   cmd = "Wtf",
  --   config = function()
  --     require('wtf').setup({
  --       -- Directory for storing chat files
  --       chat_dir = vim.fn.stdpath("data"):gsub("/$", "") .. "/wtf/chats",
  --       -- Default AI popup type
  --       popup_type = "popup", -- | "horizontal" | "vertical",
  --       -- The default provider
  --       provider = "deepseek", -- "anthropic" | "copilot" | "deepseek" | "gemini" | "grok" | "ollama" | "openai",
  --       -- Configure providers
  --       providers = {
  --         deepseek = {
  --           -- An alternative way to set your API key
  --           api_key = function() os.getenv("OPENROUTER_API_KEY") end,
  --           -- Your preferred model
  --           model_id = "deepseek-chat",
  --         },
  --       },
  --       -- Set your preferred language for the response
  --       language = "english",
  --       -- Any additional instructions
  --       additional_instructions = "Start the reply with 'OH HAI THERE'",
  --       -- Default search engine, can be overridden by passing an option to WtfSeatch
  --       search_engine = "google", -- "google" | "duck_duck_go" | "stack_overflow" | "github" | "phind" | "perplexity",
  --       -- Picker for history search (telescope, snacks, or fzf-lua)
  --       picker = "telescope", -- | "snacks" | "fzf-lua",
  --       -- Callbacks
  --       hooks = {
  --         request_started = nil,
  --         request_finished = nil,
  --       },
  --       -- Add custom colours
  --       winhighlight = "Normal:Normal,FloatBorder:FloatBorder",
  --     })
  --   end,
  --   keys = {
  --     {
  --       "<leader>bd",
  --       mode = { "n", "x" },
  --       function()
  --         require("wtf").diagnose()
  --       end,
  --       desc = "Debug diagnostic with AI",
  --     },
  --     {
  --       "<leader>bf",
  --       mode = { "n", "x" },
  --       function()
  --         require("wtf").fix()
  --       end,
  --       desc = "Fix diagnostic with AI",
  --     },
  --     {
  --       mode = { "n" },
  --       "<leader>bs",
  --       function()
  --         require("wtf").search()
  --       end,
  --       desc = "Search diagnostic with Google",
  --     },
  --     {
  --       mode = { "n" },
  --       "<leader>bp",
  --       function()
  --         require("wtf").pick_provider()
  --       end,
  --       desc = "Pick provider",
  --     },
  --     {
  --       mode = { "n" },
  --       "<leader>bh",
  --       function()
  --         require("wtf").history()
  --       end,
  --       desc = "Populate the quickfix list with previous chat history",
  --     },
  --     {
  --       mode = { "n" },
  --       "<leader>bg",
  --       function()
  --         require("wtf").grep_history()
  --       end,
  --       desc = "Grep previous chat history with Telescope",
  --     },
  --   },
  -- },
  -- {
  --   "zbirenbaum/copilot.lua",
  --   dependencies = {
  --     "copilotlsp-nvim/copilot-lsp", -- (optional) for NES functionality
  --   },
  --   cmd = "Copilot",
  --   event = "InsertEnter",
  --   config = function()
  --     require("copilot").setup({
  --       panel = {
  --         enabled = true,
  --         auto_refresh = false,
  --         keymap = {
  --           jump_prev = "[[",
  --           jump_next = "]]",
  --           accept = "<CR>",
  --           refresh = "gr",
  --           open = "<M-CR>"
  --         },
  --         layout = {
  --           position = "bottom", -- | top | left | right | bottom |
  --           ratio = 0.4
  --         },
  --       },
  --       suggestion = {
  --         enabled = true,
  --         auto_trigger = false,
  --         hide_during_completion = true,
  --         debounce = 75,
  --         trigger_on_accept = true,
  --         keymap = {
  --           accept = "<M-l>",
  --           accept_word = false,
  --           accept_line = false,
  --           next = "<M-]>",
  --           prev = "<M-[>",
  --           dismiss = "<C-]>",
  --         },
  --       },
  --       nes = {
  --         enabled = false, -- requires copilot-lsp as a dependency
  --         auto_trigger = false,
  --         keymap = {
  --           accept_and_goto = false,
  --           accept = false,
  --           dismiss = false,
  --         },
  --       },
  --     })
  --   end,
  -- },
  -- {
  --   "CopilotC-Nvim/CopilotChat.nvim",
  --   dependencies = {
  --     { "nvim-lua/plenary.nvim", branch = "master" },
  --   },
  --   build = "make tiktoken",
  --   config = function()
  --     -- Auto-command to customize chat buffer behavior
  --     vim.api.nvim_create_autocmd('BufEnter', {
  --       pattern = 'copilot-*',
  --       callback = function()
  --         vim.opt_local.relativenumber = false
  --         vim.opt_local.number = false
  --         vim.opt_local.conceallevel = 0
  --       end,
  --     })
  --     -- vim.keymap.set({ "n" }, "<Leader>b", "<Cmd>CopilotChatToggle<CR>", { silent = true })
  --   end,
  --   opts = {
  --     model = 'gpt-4.1',           -- AI model to use
  --     temperature = 0.1,           -- Lower = focused, higher = creative
  --     auto_insert_mode = true,     -- Enter insert mode when opening
  --     window = {
  --       layout = 'float',
  --       width = 80, -- Fixed width in columns
  --       height = 20, -- Fixed height in rows
  --       border = 'rounded', -- 'single', 'double', 'rounded', 'solid'
  --       title = '🤖 AI Assistant',
  --       zindex = 100, -- Ensure window stays on top
  --     },
  --
  --     headers = {
  --       user = '👤 You',
  --       assistant = '🤖 Copilot',
  --       tool = '🔧 Tool',
  --     },
  --
  --     separator = '━━',
  --     auto_fold = true, -- Automatically folds non-assistant messages
  --   },
  -- },
}

